version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.1"
      MEMORY: "6G"
      MAX_PLAYERS: "10"
      MODRINTH_PROJECTS: "geyser,viaversion,viabackwards,viarewind"
      MODRINTH_ALLOWED_VERSION_TYPE: "beta"
      ONLINE_MODE: "false"
      ENABLE_AUTOPAUSE: "true"
      # Aternos sometimes uses weird level names, we explicitly set it to world
      LEVEL: "world"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 8G
    volumes:
      - ./data:/data
    restart: unless-stopped
